# -*- coding: utf-8 -*-
"""Sandustry 材料数据（L0：官方 wiki wiki.hoodedhorse.com/Sandustry，browser-bridge 抓取 2026-08-17）。
版本戳：(v0.5.4, 2026-08-17)。专有名词保留英文。"""

MATERIALS_VERSION = {"version": "v0.5.4", "captured": "2026-08-17"}

MATERIALS = [
    {
        "name": "Amethelis",
        "props": {"Density": "40", "Matter Type": "Wisp", "Obtained From": "Flower", "Processed By": "Dryer", "Byproducts": "Dry Amethelis", "Burnable": "No", "Wettable": "No", "Launchable": "Yes"},
        "overview": "Amethelis grows as petals on Flowers. When the Flower is destroyed, 4 Amethelis and 1 Gold will be dropped. Amethelis has a special matter type, Wisp, which causes it to drift side to side when falling.",
    },
    {
        "name": "Auralite",
        "props": {"Matter Type": "Solid", "Obtained From": "Aurixite", "Processed By": "Aura Extractor", "Byproducts": "Aura", "Burnable": "No", "Wettable": "No", "Launchable": "No"},
        "overview": "",
    },
    {
        "name": "Aurixite",
        "props": {"Matter Type": "Solid", "Obtained From": "Florin", "Processed By": "Shaker", "Byproducts": "Auralite", "Burnable": "No", "Wettable": "No", "Launchable": "Yes"},
        "overview": "",
    },
    {
        "name": "Burnt_Residue",
        "props": {"Interactions": "⬇️", "Density": "50", "Matter Type": "Solid", "Obtained From": "Residue", "Processed By": "Kinetic Press", "Byproducts": "Gold, Seed", "Burnable": "No", "Wettable": "No", "Launchable": "Yes"},
        "overview": "Burnt Residue is created by igniting Residue. This can be done manually with a Flamethrower or the napalm upgrade of the Rocket Launcher. It can be automated with a Pyro Dispenser, or by running Residue over Lava trapped in Filters.",
    },
    {
        "name": "Cinder",
        "props": {"Interactions": "🔥", "Density": "50", "Matter Type": "Solid", "Obtained From": "Scoria", "Processed By": "Fire", "Byproducts": "Lava", "Burnable": "Yes", "Wettable": "No", "Launchable": "Yes"},
        "overview": "Cinder is created by destroying Scoria. It can be transported, and then burned with the Flamethrower to (re)create Lava.",
    },
    {
        "name": "Copper",
        "props": {"Matter Type": "Solid", "Obtained From": "Copper Ore", "Processed By": "Smelter", "Byproducts": "Liquid Copper", "Burnable": "No", "Wettable": "No", "Launchable": "Yes"},
        "overview": "Copper is a solid material extracted from Copper Ore.",
    },
    {
        "name": "Copper_Ore",
        "props": {"HP": "12", "Yields": "Copper", "Burnable": "No", "Meltable": "No"},
        "overview": "Copper Ore can be found in pockets underground; digging it produces Copper, which can be used in further processes.",
    },
    {
        "name": "Crackstone",
        "props": {"HP": "1", "Yields": "Nothing", "Burnable": "No", "Meltable": "No"},
        "overview": "Crackstone is a hard material that can only be broken with more advanced digging tools.",
    },
    {
        "name": "Depleted_Steam",
        "props": {"Density": "0", "Matter Type": "Gas", "Obtained From": "Consuming Steam", "Processed By": "Condenser", "Byproducts": "Water", "Burnable": "No", "Wettable": "No", "Launchable": "No"},
        "overview": "Depleted Steam is generated by processing Steam with Steam Turbine. Depleted Steam will rise up until it encounters a ceiling and pool there (like Water does on the floor). If there is no ceiling above the Depleted Steam, it will continue to rise unt",
    },
    {
        "name": "Dirt",
        "props": {"HP": "4", "Yields": "Sand", "Burnable": "No", "Meltable": "No"},
        "overview": "Dirt is the primary source of Sand. You will spend a *lot* of time digging it.",
    },
    {
        "name": "Dry_Amethelis",
        "props": {"Interactions": "🔥", "Matter Type": "Solid", "Obtained From": "Amethelis", "Processed By": "Fire", "Byproducts": "Florin", "Burnable": "Yes", "Wettable": "No", "Launchable": "Yes"},
        "overview": "",
    },
    {
        "name": "Dune",
        "props": {"HP": "1", "Yields": "Sunsand", "Burnable": "No", "Meltable": "No"},
        "overview": "Dunes can be found in the desert.",
    },
    {
        "name": "Florin",
        "props": {"Processed By": "N/A", "Byproducts": "N/A", "Burnable": "No", "Wettable": "No", "Launchable": "No"},
        "overview": "",
    },
    {
        "name": "Florinol",
        "props": {"Matter Type": "Liquid", "Obtained From": "Florin", "Processed By": "Synthesizer", "Byproducts": "Aurixite", "Burnable": "No", "Wettable": "No", "Launchable": "No"},
        "overview": "Florinol is the first resource in Sandustry that allows you to generate Energy.",
    },
    {
        "name": "Florinol_Soil",
        "props": {"HP": "1", "Yields": "Florinol", "Burnable": "Yes", "Meltable": "No"},
        "overview": "Florinol Soil is left behind when the energy in a Florinol Battery is depleted.",
    },
    {
        "name": "Flower",
        "props": {"Obtained From": "Seed", "Processed By": "N/A", "Byproducts": "Amethelis, Gold", "Burnable": "Yes", "Wettable": "No", "Launchable": "No"},
        "overview": "A Flower grows when a Wet Seed is placed on a Planter Box. Flowers are destructible by weapons or Fire to drop Gold and Amethelis. Each Flower is made up of a stem of Moss and a head of 4 Amethelis and 1 Gold.",
    },
    {
        "name": "Fluxite",
        "props": {"HP": "3", "Yields": "F", "Burnable": "No", "Meltable": "No"},
        "overview": "Fluxite is used to upgrade your tools, weapons and drones. Fluxite can be found naturally generated in the world, often in small amounts.",
    },
    {
        "name": "Frostbed",
        "props": {"HP": "1", "Yields": "Snow", "Burnable": "No", "Meltable": "No"},
        "overview": "Frostbed is frozen ground; it is too hard to be melted, and must be broken up with digging tools.",
    },
    {
        "name": "Gold",
        "props": {"Interactions": "💰", "Density": "300", "Matter Type": "Solid", "Obtained From": "Shaker, Kinetic Press, Flower", "Processed By": "Smelter", "Byproducts": "N/A", "Burnable": "No", "Wettable": "No", "Launchable": "Yes"},
        "overview": "Gold is used to Research new technologies, and so is one of the two major materials required for game progression (the other being Fluxite). Gold can be obtained as a byproduct of most processing in the game. In order to be counted towards the player",
    },
    {
        "name": "Ice",
        "props": {"HP": "??", "Yields": "Water", "Burnable": "No", "Meltable": "Yes"},
        "overview": "Ice can be found naturally in the world. It is also formed when Snow comes into contact with Water.",
    },
    {
        "name": "Indestructible",
        "props": {"Damaged By": "Nothing", "HP": "∞", "Yields": "Nothing", "Burnable": "No", "Meltable": "No"},
        "overview": "The bedrock of the world is Indestructible. As the name suggests, it is not possible to dig, damage or in any way alter bedrock.",
    },
    {
        "name": "Lava",
        "props": {"Interactions": "❄️, 💧", "Density": "75", "Matter Type": "Liquid", "Obtained From": "Cinder, Fire", "Processed By": "Cryoblaster", "Byproducts": "Scoria", "Burnable": "No", "Wettable": "No", "Launchable": "No"},
        "overview": "Lava occurs naturally deep underground in the Lava Cave, but it can be moved around your factory by using the Cinder process.",
    },
    {
        "name": "Limestone",
        "props": {"HP": "40", "Yields": "Nothing", "Burnable": "No", "Meltable": "No"},
        "overview": "Limestone appears in mysterious desert structures.",
    },
    {
        "name": "Liquid_Copper",
        "props": {"Matter Type": "Liquid", "Obtained From": "Copper", "Processed By": "Copper Mold", "Byproducts": "None", "Burnable": "No", "Wettable": "No", "Launchable": "No"},
        "overview": "Liquid Copper is the liquified form of Copper. It can then be poured into Copper Molds.",
    },
    {
        "name": "Liquid_Gold",
        "props": {"Matter Type": "Liquid", "Obtained From": "Smelter", "Processed By": "N/A", "Byproducts": "N/A", "Burnable": "No", "Wettable": "No", "Launchable": "No"},
        "overview": "Liquid Gold is an alternate form of Gold, which is used to Research new technologies.",
    },
    {
        "name": "Mooncrystal",
        "props": {"HP": "40", "Yields": "Moonhop", "Burnable": "No", "Meltable": "No"},
        "overview": "Mooncrystal can be found in small outcrops, often deep underground.",
    },
    {
        "name": "Moonhop",
        "props": {"Processed By": "N/A", "Byproducts": "N/A", "Burnable": "No", "Wettable": "No", "Launchable": "No"},
        "overview": "",
    },
    {
        "name": "Moss",
        "props": {"HP": "1", "Yields": "Nothing", "Burnable": "Yes", "Meltable": "No"},
        "overview": "Moss can be found growing in caves underground.",
    },
    {
        "name": "Prismaline",
        "props": {"Processed By": "N/A", "Byproducts": "N/A", "Burnable": "No", "Wettable": "No", "Launchable": "No"},
        "overview": "",
    },
    {
        "name": "Prismite",
        "props": {"Matter Type": "Solid", "Processed By": "N/A", "Byproducts": "N/A", "Burnable": "No", "Wettable": "No", "Launchable": "No"},
        "overview": "",
    },
    {
        "name": "Puff",
        "props": {"HP": "1", "Yields": "Nothing", "Burnable": "No", "Meltable": "No"},
        "overview": "Puff is an ephemeral terrain that collapses into nothing at the slightest touch.",
    },
    {
        "name": "Redsand",
        "props": {"Density": "160", "Matter Type": "Solid", "Obtained From": "Redsoil", "Processed By": "Combining with Void Petals", "Byproducts": "Voidbloom", "Burnable": "No", "Wettable": "No", "Launchable": "Yes"},
        "overview": "Redsand is combined with Void Petals to create Voidbloom and, in turn, Fluxite.",
    },
    {
        "name": "Redsoil",
        "props": {"HP": "20", "Yields": "Redsand", "Burnable": "No", "Meltable": "No"},
        "overview": "Redsoil is the source of Redsand. You can find large pockets of it underground, often at middle to lower depths.",
    },
    {
        "name": "Residue",
        "props": {"Interactions": "🔥", "Density": "50", "Matter Type": "Slushy", "Obtained From": "Wet Sand", "Processed By": "Fire", "Byproducts": "Burnt Residue", "Burnable": "Yes", "Wettable": "No", "Launchable": "Yes"},
        "overview": "Residue is produced by dropping Wet Sand on a Shaker. Residue must then be burned, typically with Lava or a Flamethrower, to produce Burnt Residue.",
    },
    {
        "name": "Sand",
        "props": {"Interactions": "💧", "Density": "150", "Matter Type": "Solid", "Obtained From": "Dirt", "Processed By": "Water", "Byproducts": "Wet Sand", "Burnable": "No", "Wettable": "Yes", "Launchable": "Yes"},
        "overview": "Sand is dropped from destroying Dirt. It must be combined with Water to create Wet Sand.",
    },
    {
        "name": "Scoria",
        "props": {"HP": "10", "Yields": "Cinder", "Burnable": "No", "Meltable": "No"},
        "overview": "Scoria does not occur naturally; it is the product of freezing Lava.",
    },
    {
        "name": "Seed",
        "props": {"Interactions": "💧", "Density": "150", "Matter Type": "Solid", "Obtained From": "Kinetic Press", "Processed By": "Combine with Water", "Byproducts": "Wet Seed", "Burnable": "No", "Wettable": "Yes", "Launchable": "Yes"},
        "overview": "Seeds are created by processing Burnt Residue with a Kinetic Press. Seeds must then be wet with Water to create Wet Seeds.",
    },
    {
        "name": "Snow",
        "props": {"Interactions": "🔥", "Density": "150", "Matter Type": "Solid", "Obtained From": "Cryoblaster, Frostbed", "Processed By": "Fire", "Byproducts": "Water", "Burnable": "Yes", "Wettable": "No", "Launchable": "Yes"},
        "overview": "Snow is obtained when using the Cryoblaster or by digging Frostbed. When burned, it creates Steam. This is currently the only renewable source of Water in the game besides duplication. When Snow comes into contact with Lava, the Lava changes into Sco",
    },
    {
        "name": "Solidite",
        "props": {"HP": "1", "Yields": "Nothing", "Burnable": "No", "Meltable": "No"},
        "overview": "Solidite is produced using the Caulk Blaster.",
    },
    {
        "name": "Steam",
        "props": {"Density": "0", "Matter Type": "Gas", "Obtained From": "Heating Water or Snow", "Processed By": "Reaching the sky", "Byproducts": "Water", "Burnable": "No", "Wettable": "No", "Launchable": "No"},
        "overview": "Steam is generated by heating Water or Snow with Fire. This can be done manually with a Flamethrower or the napalm upgrade of the Rocket Launcher. Steam will rise up until it encounters a ceiling and pool there (like Water does on the floor). If ther",
    },
    {
        "name": "Stone",
        "props": {"HP": "8", "Yields": "Nothing", "Burnable": "No", "Meltable": "No"},
        "overview": "Stone is a hard material that can only be broken with more advanced digging tools.",
    },
    {
        "name": "Sunsand",
        "props": {"Obtained From": "Dune", "Processed By": "N/A", "Byproducts": "N/A", "Burnable": "No", "Wettable": "No", "Launchable": "Yes"},
        "overview": "Sunsand is dropped by destroying Dune. When not falling it turns back to Dune.",
    },
    {
        "name": "Vine",
        "props": {"HP": "1", "Yields": "Nothing", "Burnable": "Yes", "Meltable": "No"},
        "overview": "Vines grow from Wet Seed when placed on Planter Boxes; they support the resulting Flower.",
    },
    {
        "name": "Void_Husk",
        "props": {"Processed By": "N/A", "Byproducts": "N/A", "Burnable": "No", "Wettable": "No", "Launchable": "No"},
        "overview": "",
    },
    {
        "name": "Void_Juice",
        "props": {"Processed By": "N/A", "Byproducts": "N/A", "Burnable": "No", "Wettable": "No", "Launchable": "No"},
        "overview": "",
    },
    {
        "name": "Void_Seed",
        "props": {"Processed By": "N/A", "Byproducts": "N/A", "Burnable": "No", "Wettable": "No", "Launchable": "No"},
        "overview": "",
    },
    {
        "name": "Voidbloom",
        "props": {"Interactions": "🔮", "Density": "30", "Matter Type": "Slushy", "Obtained From": "Combining Void Petals and Redsand", "Processed By": "Flux Emanator", "Byproducts": "Fluxite", "Burnable": "No", "Wettable": "No", "Launchable": "Yes"},
        "overview": "Voidbloom is created by combining of Void Petals and Redsand and is used to create Fluxite.",
    },
    {
        "name": "Water",
        "props": {"Interactions": "🔥, ❄️", "Density": "100", "Matter Type": "Liquid", "Obtained From": "Ice, Steam", "Processed By": "Fire, Snow", "Byproducts": "Steam, Ice", "Burnable": "Yes", "Wettable": "No", "Launchable": "No"},
        "overview": "Water is a critical resource in Sandustry, used for wetting Sand and Seeds. Large volumes of Water are required for an efficient factory, so players must sufficiently plan to obtain sustainable sources.",
    },
    {
        "name": "Wet_Sand",
        "props": {"Interactions": "↔️", "Density": "150", "Matter Type": "Slushy", "Obtained From": "Sand", "Processed By": "Shakers", "Byproducts": "Gold, Residue", "Burnable": "No", "Wettable": "No", "Launchable": "Yes"},
        "overview": "Wet Sand is created by mixing Sand with Water. Wet Sand is then processed by being dropped on a Shaker, producing Gold and Residue.",
    },
    {
        "name": "Wet_Seed",
        "props": {"Interactions": "🪴", "Density": "100", "Matter Type": "Slushy", "Obtained From": "Seed, Water", "Processed By": "Planter Box", "Byproducts": "Flower", "Burnable": "No", "Wettable": "No", "Launchable": "Yes"},
        "overview": "Wet Seeds are created by combining Seeds with Water. Unlike dry Seeds, Wet Seeds are the same density as Water, meaning they can remain suspended in the water instead of sinking. This can make effective Wet Seed production a difficult challenge. Wet ",
    },
]
